### ISSUE TITLE
Is it useful to propose the change of color of a car ?

### ISSUE THREAD

**Issue by texx94** [HEIG-Boom/heigvd-pro-a-02-SiTR#144]
Car have already a particular color according to the controller "inside". Is it meaningful to allow user to change it ? I think the user don't want to have a rainbow traffic jam.

**Comment by Laykel** [comment]
Good question. We thought it would be useful to allow the user to follow a specific car visually.

It's true that it shouldn't be a priority. You can remove this field if you want.
