### ISSUE TITLE
Complete Vehicle's interface to be read by the GUI.

### ISSUE THREAD

**Issue by Laykel** [HEIG-Boom/heigvd-pro-a-02-SiTR#54]
The Vehicle should provide `getters` for the following data.

- (Coordinates of start position and destination) - when a lane is available
- Average waiting time
- Potential accidents counter

It is to be used by the `CarControlPanel`.

**Comment by Waltharnack** [comment]
Should we really provides start position and destination as coordinates @Laykel ?
Wouldn't it be a start lane and end lane ?

**Comment by Laykel** [comment]
In the mockup, we decided to show start position and end position of a vehicle as coordinates.
We could change that, though.

It might be weird because we need the lane to get our absolute coordinates... But we'll try it out and see when a lane is available.

**Comment by Laykel** [comment]
Waiting time is not yet implemented, but the interface is there. Closing this,
