### ISSUE TITLE
Generate vehicle traffic in simulation

### ISSUE THREAD

**Issue by Waltharnack** [HEIG-Boom/heigvd-pro-a-02-SiTR#89]
- with vehicule having their respectives front vehicle
- each deltaT add a vehicle of each controller types that doesn't already have all their vehicles in the traffic
- vehicles must have a origin and destination, with segment lane if possible

**Comment by Laykel** [comment]
I'm paging @texx94 because this needs a means of easily getting the number of each controllers wanted, and their behaviour from the `SettingsPanel`. #101

**Comment by Laykel** [comment]
**Very** basic version implemented in #106 with the `generateTraffic` method.

We still need to manage most vehicles properties, including positions and front vehicles.

**Comment by Laykel** [comment]
There's still a lot of work to do on this, but other issues are opened for that. 
I'll close this one.
